### ISSUE TITLE
Failure to connect to MongoDB

### ISSUE THREAD

**Issue by mturilli** [mturilli/aimes.emanager#7]
Yadu reported the following issue (full trace at http://pastebin.com/6QLK8rbe):

```
CUs descriptions for Stage_1
Tasks translated into CUs : Stage_1_Stage_1_0  : Stage_1_Stage_1_1  : Stage_1_Stage_1_2  : Stage_1_Stage_1_3  : Stage_1_Stage_1_4  : Stage_1_Stage_1_5  : Stage_1_Stage_1_6  : Stage_1_Stage_1_7  : Stage_1_Stage_1_8  : Stage_1_Stage_1_9  : Stage_1_Stage_1_10  : Stage_1_Stage_1_11  : Stage_1_Stage_1_12  : Stage_1_Stage_1_13  : StException in thread OutputFileTransferWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/yadu/Virtualenvs/AIMES-DEMO-SC2014/local/lib/python2.7/site-packages/radical/pilot/controller/output_file_transfer_worker.py", line 261, in run
    "statehistory": {"state": DONE, "timestamp": ts}
  File "/home/yadu/Virtualenvs/AIMES-DEMO-SC2014/local/lib/python2.7/site-packages/pymongo/collection.py", line 1738, in find_and_modify
    **kwargs)
  File "/home/yadu/Virtualenvs/AIMES-DEMO-SC2014/local/lib/python2.7/site-packages/pymongo/database.py", line 439, in command
    uuid_subtype, compile_re, **kwargs)[0]
  File "/home/yadu/Virtualenvs/AIMES-DEMO-SC2014/local/lib/python2.7/site-packages/pymongo/database.py", line 338, in _command
    for doc in cursor:
  File "/home/yadu/Virtualenvs/AIMES-DEMO-SC2014/local/lib/python2.7/site-packages/pymongo/cursor.py", line 1076, in next
    if len(self.__data) or self._refresh():
  File "/home/yadu/Virtualenvs/AIMES-DEMO-SC2014/local/lib/python2.7/site-packages/pymongo/cursor.py", line 1020, in _refresh
    self.__uuid_subtype))
  File "/home/yadu/Virtualenvs/AIMES-DEMO-SC2014/local/lib/python2.7/site-packages/pymongo/cursor.py", line 933, in __send_message
    res = client._send_message_with_response(message, **kwargs)
  File "/home/yadu/Virtualenvs/AIMES-DEMO-SC2014/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1217, in _send_message_with_response
    raise AutoReconnect(str(e))
AutoReconnect: [Errno 22] Invalid argument
```

Upon investigation, an error also with `aimes-bundle-manager` not uploading bundle data into the specified database.

**Comment by mturilli** [comment]
The following definition in the bundle conf leads to silent failure:

```
cluster_type=slurm hostname=stampede.tacc.xsede.org username="name"
```

apparently, due to the double commas around the username. We may want to open a ticket with bundles.

**Comment by mturilli** [comment]
Upon further inspection, the issue seems to be related to the version of saga-python. @yadudoc would you mind to test the demo again using the following command to install saga-python from the development branch?

```
pip install --upgrade git+https://github.com/radical-cybertools/saga-python.git@devel#egg=saga-python
```
